{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "8.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-8.1.6.jar",
          "url": "core-ng-mongo-test-8.1.6.jar",
          "size": 2394,
          "sha512": "facf1d1b9f57b33cefb8a276cdd4346e1999c4c8db82565d55946e2ed7af268cfa4bdcffde244153bf0883fc19ed0aef32eb1e7cfa9d877c55757945a61bc7a8",
          "sha256": "e0b6b0f6b3ee03550b35b946b5a12ee05ad75d1b6d75a042fa507f53c7ee6a92",
          "sha1": "8ebdf266fa6f3393c911dd81b719b623eb39f3f3",
          "md5": "97b9420cedb42cf6f01b292c34cc2f33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "8.1.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "8.1.6"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.44.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-8.1.6.jar",
          "url": "core-ng-mongo-test-8.1.6.jar",
          "size": 2394,
          "sha512": "facf1d1b9f57b33cefb8a276cdd4346e1999c4c8db82565d55946e2ed7af268cfa4bdcffde244153bf0883fc19ed0aef32eb1e7cfa9d877c55757945a61bc7a8",
          "sha256": "e0b6b0f6b3ee03550b35b946b5a12ee05ad75d1b6d75a042fa507f53c7ee6a92",
          "sha1": "8ebdf266fa6f3393c911dd81b719b623eb39f3f3",
          "md5": "97b9420cedb42cf6f01b292c34cc2f33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-8.1.6-sources.jar",
          "url": "core-ng-mongo-test-8.1.6-sources.jar",
          "size": 1727,
          "sha512": "1a367f95618bd3626bd4bc2066d7f94e6b01d6fea8abaf0960d8917b6e8ad88524ef06eb30202128551556f6848bf359dd52e13332f7a3c9ccd1e92363e76a3e",
          "sha256": "0af482b2d590174100c0912cc62655e793bd7d88459fd209de384c675276ce43",
          "sha1": "cc661d47eb4f54b1d17e838e6ad8447f2f885159",
          "md5": "387336902fe38d1b7fd5342b1c6dc63e"
        }
      ]
    }
  ]
}
